export const TOGGLE_NAV = 'TOGGLE_NAV'
export const SET_MOBILE_STATUS = 'SET_MOBILE_STATUS'
export const SET_COOKIE_ACCEPTED = 'SET_COOKIE_ACCEPTED'
export const SEARCH = 'SEARCH'
export const GET_LATEST_ITEMS = 'GET_LATEST_ITEMS'
export const GET_USER_BOOKMARKS = 'GET_USER_BOOKMARKS'
export const CLEAR_GLOBAL = 'CLEAR_GLOBAL'
export const GET_BASE_STATS = 'GET_BASE_STATS'

export default {
  TOGGLE_NAV,
  SET_MOBILE_STATUS,
  SET_COOKIE_ACCEPTED,
  SEARCH,
  GET_LATEST_ITEMS,
  GET_USER_BOOKMARKS,
  CLEAR_GLOBAL,
  GET_BASE_STATS
}
