export const FETCH_ALL = 'FETCH_ALL'
export const FETCH_BY_SLUG = 'FETCH_BY_SLUG'
export const FETCH_BY_AUTHOR_SLUG = 'FETCH_BY_AUTHOR_SLUG'
export const FETCH_PAGINATE = 'FETCH_PAGINATE'
export const CLEAR_ARTICLES = 'CLEAR_ARTICLES'
export const TOGGLE_BOOKMARK = 'TOGGLE_BOOKMARK'

export default {
  FETCH_ALL,
  FETCH_PAGINATE,
  CLEAR_ARTICLES,
  FETCH_BY_AUTHOR_SLUG,
  FETCH_BY_SLUG,
  TOGGLE_BOOKMARK
}
