export const FETCH_ALL = 'FETCH_ALL'
export const FETCH_BY_SLUG = 'FETCH_BY_SLUG'
export const FETCH_BY_CHANNEL_SLUG = 'FETCH_BY_CHANNEL_SLUG'
export const FETCH_PAGINATE = 'FETCH_PAGINATE'
export const CLEAR_VIDEOS = 'CLEAR_VIDEOS'
export const TOGGLE_BOOKMARK = 'TOGGLE_BOOKMARK'
export const FETCH_CHANNELS = 'FETCH_CHANNELS'

export default {
  FETCH_ALL,
  FETCH_PAGINATE,
  CLEAR_VIDEOS,
  FETCH_BY_CHANNEL_SLUG,
  FETCH_BY_SLUG,
  TOGGLE_BOOKMARK,
  FETCH_CHANNELS
}
