export const FETCH_ALL = 'FETCH_ALL'
export const FETCH_BY_SLUG = 'FETCH_BY_SLUG'
export const FETCH_PAGINATE = 'FETCH_PAGINATE'
export const CLEAR_VIDEOS = 'CLEAR_VIDEOS'

export default {
  FETCH_ALL,
  FETCH_PAGINATE,
  CLEAR_VIDEOS,
  FETCH_BY_SLUG
}
