export const FETCH_ALL = 'FETCH_ALL'
export const FETCH_BY_SLUG = 'FETCH_BY_SLUG'
export const FETCH_BY_SHOW_SLUG = 'FETCH_BY_SHOW_SLUG'
export const FETCH_PAGINATE = 'FETCH_PAGINATE'
export const CLEAR_PODCASTS = 'CLEAR_PODCASTS'
export const TOGGLE_BOOKMARK = 'TOGGLE_BOOKMARK'

export default {
  FETCH_ALL,
  FETCH_PAGINATE,
  CLEAR_PODCASTS,
  FETCH_BY_SHOW_SLUG,
  FETCH_BY_SLUG,
  TOGGLE_BOOKMARK
}
