export const FETCH_ONLINE = 'FETCH_ONLINE'
export const FETCH_LAST_ONLINE = 'FETCH_LAST_ONLINE'
export const FETCH_STREAM_TAGS = 'FETCH_STREAM_TAGS'
export const FETCH_STREAM_BY_TAG = 'FETCH_STREAM_BY_TAG'
export const CLEAR_STREAMS = 'CLEAR_STREAMS'
export const TOGGLE_BOOKMARK = 'TOGGLE_BOOKMARK'
export const FETCH_BY_SLUG = 'FETCH_BY_SLUG'

export default {
  FETCH_ONLINE,
  FETCH_LAST_ONLINE,
  FETCH_STREAM_TAGS,
  FETCH_STREAM_BY_TAG,
  CLEAR_STREAMS,
  TOGGLE_BOOKMARK,
  FETCH_BY_SLUG
}
